### ISSUE TITLE
Crashes on Android 14

### ISSUE THREAD

**Issue by florian-obernberger** [Kr0oked/Metronome#20]
After updating to the latest version (1.4.3) the app crashes whenever I hit play to start the metronome

**Comment by Kr0oked** [comment]
Thanks for reporting the issue.
I just released a new version that fixes this issue: https://github.com/Kr0oked/Metronome/releases/tag/v1.4.4
The issue was already solved in https://github.com/Kr0oked/Metronome/pull/19
It probably takes a few days until the new version is available at the app stores.
